In [2]:
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [3]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## Preprocess the data
## Drop innecessory featues
data= data.drop(['RowNumber','CustomerId','Surname',],axis=1)

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
##Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [7]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
## Combines all the columns with the original data
data = pd.concat([data.drop('Geography',axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [9]:
X=data.drop('EstimatedSalary', axis=1)
y=data['EstimatedSalary']

In [10]:
## Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Scale these faetures using standard Scaler
scaler = StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [11]:
## Save the encoders and scaler for future use
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Regression Problem Statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  ## iNput layer
    Dense(32, activation='relu'), # HL1
    Dense(1) # Output layer by default use linear activation function which is used for regression
]
)

##Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

c:\Users\HP\OneDrive\Desktop\Desktop1\Desktop 2\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
##Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

##Set up the Tensorboard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
## setup early stopping
early_stopping_callback= EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
## Training the model
history= model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - loss: 100383.5938 - mae: 100383.5938 - val_loss: 98538.5625 - val_mae: 98538.5625
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 99704.5938 - mae: 99704.5938 - val_loss: 97162.3828 - val_mae: 97162.3828
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 97296.0078 - mae: 97296.0078 - val_loss: 93610.3984 - val_mae: 93610.3984
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 92518.5156 - mae: 92518.5156 - val_loss: 87636.0234 - val_mae: 87636.0234
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 85458.3203 - mae: 85458.3203 - val_loss: 79727.3047 - val_mae: 79727.3047
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 76904.8984 - mae: 76904.8984 - val_loss: 71032.1094 - val_mae: 71032.1094
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 68238.9453 - mae: 68238.9453 - val_loss: 63285.7188 - val_mae: 63285.7188
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 60952.0117 - mae: 60952.0117 - val_loss: 57224.8516 - val_mae: 57224.8516
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 55757.4023 - mae: 55757.4023 - val_loss: 53472.4844 - val_mae: 53472.4844
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 52699.5352 - mae: 52699.5352 - val_loss: 51704.5586 - val_mae: 51704.5586
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 51240.1250 - mae: 51240.1250 - val_loss: 51013.4297 - val_mae: 51013.4297
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50634.7617 - mae: 50634.7617 - val_loss: 50810.5195 - val_mae: 50810.5195
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50377.8477 - mae: 50377.8477 - val_loss: 50739.1367 - val_mae: 50739.1367
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50263.3398 - mae: 50263.3398 - val_loss: 50701.6719 - val_mae: 50701.6719
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50182.9492 - mae: 50182.9492 - val_loss: 50670.5039 - val_mae: 50670.5039
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50123.5547 - mae: 50123.5547 - val_loss: 50637.2539 - val_mae: 50637.2539
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 50067.6875 - mae: 50067.6875 - val_loss: 50609.2188 - val_mae: 50609.2188
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50025.2344 - mae: 50025.2344 - val_loss: 50584.0664 - val_mae: 50584.0664
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49977.4883 - mae: 49977.4883 - val_loss: 50564.0508 - val_mae: 50564.0508
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49944.4883 - mae: 49944.4883 - val_loss: 50545.8359 - val_mae: 50545.8359
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49910.0938 - mae: 49910.0938 - val_loss: 50534.6094 - val_mae: 50534.6094
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49878.9961 - mae: 49878.9961 - val_loss: 50524.8516 - val_mae: 50524.8516
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49856.2227 - mae: 49856.2227 - val_loss: 50512.2969 - val_mae: 50512.2969
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49829.6641 - mae: 49829.6641 - val_loss: 50489.8906 - val_mae: 50489.8906
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49806.4805 - mae: 49806.4805 - val_loss: 50476.2930 - val_mae: 50476.2930
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49783.5000 - mae: 49783.5000 - val_loss: 50474.0469 - val_mae: 50474.0469
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49764.2305 - mae: 49764.2305 - val_loss: 50454.8281 - val_mae: 50454.8281
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49747.4062 - mae: 49747.4062 - val_loss: 50448.0938 - val_mae: 50448.0938
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49729.9922 - mae: 49729.9922 - val_loss: 50449.1211 - val_mae: 50449.1211
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49715.5078 - mae: 49715.5078 - val_loss: 50436.7383 - val_mae: 50436.7383
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49698.7695 - mae: 49698.7695 - val_loss: 50417.6328 - val_mae: 50417.6328
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49686.7344 - mae: 49686.7344 - val_loss: 50411.5312 - val_mae: 50411.5312
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49675.7148 - mae: 49675.7148 - val_loss: 50414.6406 - val_mae: 50414.6406
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49661.3477 - mae: 49661.3477 - val_loss: 50407.7578 - val_mae: 50407.7578
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49650.9375 - mae: 49650.9375 - val_loss: 50401.3438 - val_mae: 50401.3438
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49637.9375 - mae: 49637.9375 - val_loss: 50400.0469 - val_mae: 50400.0469
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49626.6211 - mae: 49626.6211 - val_loss: 50393.2773 - val_mae: 50393.2773
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49619.1172 - mae: 49619.1172 - val_loss: 50384.3086 - val_mae: 50384.3086
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49605.1016 - mae: 49605.1016 - val_loss: 50384.5625 - val_mae: 50384.5625
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49598.6172 - mae: 49598.6172 - val_loss: 50383.5469 - val_mae: 50383.5469
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49585.9453 - mae: 49585.9453 - val_loss: 50381.4531 - val_mae: 50381.4531
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49580.2969 - mae: 49580.2969 - val_loss: 50384.8086 - val_mae: 50384.8086
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49569.4648 - mae: 49569.4648 - val_loss: 50381.1562 - val_mae: 50381.1562
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49560.8672 - mae: 49560.8672 - val_loss: 50379.7656 - val_mae: 50379.7656
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49552.7422 - mae: 49552.7422 - val_loss: 50364.9336 - val_mae: 50364.9336
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49545.7227 - mae: 49545.7227 - val_loss: 50364.7578 - val_mae: 50364.7578
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49538.1641 - mae: 49538.1641 - val_loss: 50365.2891 - val_mae: 50365.2891
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49530.9531 - mae: 49530.9531 - val_loss: 50364.1211 - val_mae: 50364.1211
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49523.6133 - mae: 49523.6133 - val_loss: 50366.1055 - val_mae: 50366.1055
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49515.6445 - mae: 49515.6445 - val_loss: 50375.4297 - val_mae: 50375.4297
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49510.2383 - mae: 49510.2383 - val_loss: 50370.5117 - val_mae: 50370.5117
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49502.3828 - mae: 49502.3828 - val_loss: 50360.4023 - val_mae: 50360.4023
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49495.4766 - mae: 49495.4766 - val_loss: 50351.1914 - val_mae: 50351.1914
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49491.4688 - mae: 49491.4688 - val_loss: 50354.6016 - val_mae: 50354.6016
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49483.7305 - mae: 49483.7305 - val_loss: 50354.6641 - val_mae: 50354.6641
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49477.6758 - mae: 49477.6758 - val_loss: 50364.4336 - val_mae: 50364.4336
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49471.7812 - mae: 49471.7812 - val_loss: 50374.7188 - val_mae: 50374.7188
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49464.1992 - mae: 49464.1992 - val_loss: 50358.1953 - val_mae: 50358.1953
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49468.7930 - mae: 49468.7930 - val_loss: 50359.4727 - val_mae: 50359.4727
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49456.1523 - mae: 49456.1523 - val_loss: 50350.7031 - val_mae: 50350.7031
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49451.3125 - mae: 49451.3125 - val_loss: 50369.3320 - val_mae: 50369.3320
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49448.9688 - mae: 49448.9688 - val_loss: 50369.3242 - val_mae: 50369.3242
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49441.1016 - mae: 49441.1016 - val_loss: 50359.7578 - val_mae: 50359.7578
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49437.0547 - mae: 49437.0547 - val_loss: 50363.7422 - val_mae: 50363.7422
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49434.1367 - mae: 49434.1367 - val_loss: 50363.6250 - val_mae: 50363.6250
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49432.8984 - mae: 49432.8984 - val_loss: 50365.2578 - val_mae: 50365.2578
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49425.1094 - mae: 49425.1094 - val_loss: 50358.2422 - val_mae: 50358.2422
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49418.1133 - mae: 49418.1133 - val_loss: 50358.5898 - val_mae: 50358.5898
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49415.1602 - mae: 49415.1602 - val_loss: 50345.0859 - val_mae: 50345.0859
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49410.5039 - mae: 49410.5039 - val_loss: 50352.3359 - val_mae: 50352.3359
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 49407.2188 - mae: 49407.2188 - val_loss: 50367.4336 - val_mae: 50367.4336
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49407.6680 - mae: 49407.6680 - val_loss: 50358.8594 - val_mae: 50358.8594
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49399.5234 - mae: 49399.5234 - val_loss: 50357.0195 - val_mae: 50357.0195
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49398.5547 - mae: 49398.5547 - val_loss: 50351.8047 - val_mae: 50351.8047
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49394.1406 - mae: 49394.1406 - val_loss: 50354.3477 - val_mae: 50354.3477
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49388.6836 - mae: 49388.6836 - val_loss: 50361.4883 - val_mae: 50361.4883
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49387.5586 - mae: 49387.5586 - val_loss: 50365.6719 - val_mae: 50365.6719
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49385.4219 - mae: 49385.4219 - val_loss: 50366.5273 - val_mae: 50366.5273
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49379.7773 - mae: 49379.7773 - val_loss: 50363.1758 - val_mae: 50363.1758

In [18]:
%load_ext tensorboard

In [20]:
%tensorboard --logdir regressionlogs/fit

In [21]:
##Evaluate model on the test data
test_loss,test_mae= model.evaluate(X_test,y_test)
print(F"Test Mae: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 50345.0859 - mae: 50345.0859
Test Mae: 50345.0859375

In [22]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.